/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.dbModel.job.JobDAO;
import com.dbModel.job.JobDTO;
import com.dbModel.userlist.UserListDAO;
import com.dbModel.userlist.UserListDTO;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;

/**
 *
 * @author pks01
 */
public class JoinGUI extends javax.swing.JFrame {
    private JobDAO jDao;
    private UserListDAO uDao;
    private LoginGUI loginGUI;

    /**
     * Creates new form JoinGUI
     */
    public JoinGUI() {
        initComponents();

        init();
        addEvent();
    }

    public JoinGUI(String userId, String pwd) {
        this();

        tfUserId.setText(userId);
        tfPwd.setText(pwd);
    }

    public JoinGUI(String userId, String pwd, LoginGUI loginGUI) {
        this(userId, pwd);
        this.loginGUI = loginGUI;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbUserId = new javax.swing.JLabel();
        tfUserId = new javax.swing.JTextField();
        lbPwd = new javax.swing.JLabel();
        tfPwd = new javax.swing.JPasswordField();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbAge = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        lbJob = new javax.swing.JLabel();
        cbJob = new javax.swing.JComboBox<>();
        lbIntro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taIntro = new javax.swing.JTextArea();
        btnResult = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToDoList - Sign up");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbUserId.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        lbUserId.setText("아이디");

        tfUserId.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        tfUserId.setSelectionColor(new java.awt.Color(204, 204, 204));
        tfUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserIdActionPerformed(evt);
            }
        });

        lbPwd.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        lbPwd.setText("비밀번호");

        tfPwd.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        tfPwd.setSelectionColor(new java.awt.Color(204, 204, 204));

        lbName.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        lbName.setText("이름");

        tfName.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        tfName.setSelectionColor(new java.awt.Color(204, 204, 204));
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        lbAge.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        lbAge.setText("나이");

        tfAge.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        tfAge.setSelectionColor(new java.awt.Color(204, 204, 204));
        tfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAgeActionPerformed(evt);
            }
        });

        lbJob.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        lbJob.setText("직종");

        cbJob.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        cbJob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lbIntro.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        lbIntro.setText("자기소개");

        taIntro.setColumns(20);
        taIntro.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        taIntro.setLineWrap(true);
        taIntro.setRows(5);
        taIntro.setTabSize(1);
        taIntro.setAutoscrolls(false);
        taIntro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)));
        taIntro.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(taIntro);

        btnResult.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 24)); // NOI18N
        btnResult.setText("회원가입");
        btnResult.setBorder(null);
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(202, 187, 187));
        btnClose.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 24)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("닫기");
        btnClose.setBorder(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbIntro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbName)
                                .addGap(97, 97, 97)
                                .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbUserId)
                                    .addComponent(lbPwd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfUserId)
                                    .addComponent(tfPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAge)
                                    .addComponent(lbJob))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfAge, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(cbJob, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(76, 76, 76))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUserId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPwd)
                    .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAge)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJob)
                    .addComponent(cbJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(lbIntro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserIdActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResultActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoinGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnResult;
    private javax.swing.JComboBox<String> cbJob;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbIntro;
    private javax.swing.JLabel lbJob;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPwd;
    private javax.swing.JLabel lbUserId;
    private javax.swing.JTextArea taIntro;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPwd;
    private javax.swing.JTextField tfUserId;
    // End of variables declaration//GEN-END:variables


    private void init() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        btnResult.setBorderPainted(false);
        btnClose.setBorderPainted(false);

        btnResult.setContentAreaFilled(false);

        jDao = new JobDAO();
        uDao = new UserListDAO();

        try {
            setComboBox();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void setComboBox() throws SQLException {
        List<JobDTO> list = jDao.selectAll();
        Vector<String> cbList = new Vector<>();

        for(int i = 1; i < list.size(); i++) {
            JobDTO dto = list.get(i);
            cbList.add(dto.getJobTitle());
        }
        cbList.add(list.get(0).getJobTitle());

        DefaultComboBoxModel model = new DefaultComboBoxModel(cbList);
        cbJob.setModel(model);
    }

    private void addEvent() {
        btnClose.addActionListener(new ButtonEventHandler());
        btnResult.addActionListener(new ButtonEventHandler());
    }


    private class ButtonEventHandler implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                if (e.getSource() == btnClose) {
                    dispose();
                } else if (e.getSource() == btnResult) {
                    createUser();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    
    //아이디 생성 메소드
    private void createUser() throws SQLException {
        UserListDTO dto = new UserListDTO();

        String userId = tfUserId.getText();
        String pwd = tfPwd.getText();
        String name = tfName.getText();
        String inputAge = tfAge.getText();
        int age = 0;
        String selectJob = (String) cbJob.getSelectedItem();
        int jNo = 0;
        String intro = taIntro.getText();

        //아이디 유효성 검사
        if(userId == null || userId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "아이디를 입력하세요.");
            tfUserId.requestFocus();
            return;
        }
        //아이디 중복 검사
        if(!uDao.findUser(userId)) {
            JOptionPane.showMessageDialog(this, "이미 있는 아이디입니다.");
            tfUserId.requestFocus();
            return;
        }

        //비밀번호 유효성 검사
        if(pwd == null || pwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "비밀번호를 입력하세요.");
            tfPwd.requestFocus();
            return;
        }

        //나이 유효성 검사
        if(inputAge != null && !inputAge.isEmpty()) {
            for(int i = 0; i < inputAge.length(); i++){
                if(!Character.isDigit(inputAge.charAt(i))) {
                    JOptionPane.showMessageDialog(this, "나이가 유효하지 않습니다.");
                    tfAge.requestFocus();
                    return;
                }
            }
            age = Integer.parseInt(inputAge);
            if(!(0 <= age && age < 120)) {
                JOptionPane.showMessageDialog(this, "나이가 유효하지 않습니다.");
                tfAge.requestFocus();
                return;
            }
        }

        //comboBox 직종, 참조키로 반환
        jNo = jDao.selectJobTitle(selectJob);

        dto.setUserId(userId);
        dto.setPwd(pwd);
        dto.setName(name);
        dto.setAge(age);
        dto.setJno(jNo);
        dto.setIntroduction(intro);

        int cnt = uDao.insertUser(dto);
        System.out.println(cnt > 0 ? "계정생성 성공" : "계정생성 실패");

        if(cnt > 0) {
            JOptionPane.showMessageDialog(this, "계정등록 성공");
            loginGUI.tfUserId.setText(userId);
            loginGUI.tfPwd.setText(pwd);
            
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(this, "계정등록 실패");
        }
    }
}
