/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.dbModel.userlist.UserListDAO;
import com.util.UserStateUtil;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;

/**
 *
 * @author pks01
 */
public class LoginGUI extends javax.swing.JFrame {
    private UserListDAO dao;
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        
        init();
        addEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        tfUserId = new javax.swing.JTextField();
        lbPwd = new javax.swing.JLabel();
        tfPwd = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ToDoList - LOGIN");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbLogo.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ToDo List");

        lbUser.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lbUser.setText("ID");

        tfUserId.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        tfUserId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserIdActionPerformed(evt);
            }
        });

        lbPwd.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lbPwd.setText("PW");

        tfPwd.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        tfPwd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPwdActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        btnLogin.setText("Sign in");
        btnLogin.setBorder(null);
        btnLogin.setFocusPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnJoin.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        btnJoin.setText("Sign up");
        btnJoin.setBorder(null);
        btnJoin.setFocusPainted(false);
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPwd)
                            .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUserId)
                            .addComponent(tfPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lbLogo)
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPwd))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(405, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserIdActionPerformed

    private void tfPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPwdActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbPwd;
    private javax.swing.JLabel lbUser;
    public javax.swing.JPasswordField tfPwd;
    public javax.swing.JTextField tfUserId;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setLocationRelativeTo(null);
        dao = new UserListDAO();
        File fileLogoImg = new File("src/main/java/img/logo.png");
        try {
            BufferedImage img = ImageIO.read(fileLogoImg);
            lbLogo.setIcon(new ImageIcon(img));
        } catch (IOException e) {
            e.printStackTrace();
        }

        btnJoin.setBorderPainted(false);
        btnLogin.setBorderPainted(false);

        btnJoin.setContentAreaFilled(false);
        btnLogin.setContentAreaFilled(false);
    }

    private void addEvent() {
        btnLogin.addMouseListener(new MouseEventHandler());
        btnJoin.addMouseListener(new MouseEventHandler());

        btnLogin.addActionListener(new ButtonEventHandler());
        btnJoin.addActionListener(new ButtonEventHandler());

//        tfUserId.addKeyListener(new EnterEventHandler());
//        tfPwd.addKeyListener(new EnterEventHandler());
    }

//    private class EnterEventHandler extends KeyAdapter {
//        @Override
//        public void keyReleased(KeyEvent e) {
//            if(e.getKeyCode() == KeyEvent.VK_ENTER) {
//                System.out.println("Enter 입력됨");
//                if(e.getSource() == tfUserId) {
//                    tfPwd.requestFocus();
//                }else if(e.getSource() == tfPwd) {
//                    try {
//                        login();
//                    } catch (SQLException ex) {
//                        ex.printStackTrace();
//                    }
//                }
//            }
//        }
//    }

    private class MouseEventHandler extends MouseAdapter {
        @Override
        public void mouseEntered(MouseEvent e) {
            JButton jb = (JButton)e.getSource();
            jb.setContentAreaFilled(true);
            jb.setBackground(new Color(242,242,242));
            System.out.println("마우스가 " + ((JButton)e.getSource()).getText() + "에 들어옴");
        }

        @Override
        public void mouseExited(MouseEvent e) {
            JButton jb = (JButton)e.getSource();
            jb.setContentAreaFilled(false);
            jb.setBackground(new Color(255,255,255));
        }
    }

    private class ButtonEventHandler implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                if (e.getSource() == btnLogin) {
                    System.out.println("로그인 버튼 클릭");
                    login();
                } else if (e.getSource() == btnJoin) {
                    System.out.println("회원가입 버튼 클릭");
                    join();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    private void login() throws SQLException {
        String userId = tfUserId.getText();
        String pwd = tfPwd.getText();

        if(userId == null || userId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "아이디를 입력하세요.");
            tfUserId.requestFocus();
            return;
        }
        if(pwd == null || pwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "비밀번호를 입력하세요.");
            tfPwd.requestFocus();
            return;
        }

        int result = dao.loginUser(userId, pwd);

        if(result == UserStateUtil.USERID_NONE_CHECK) {
            JOptionPane.showMessageDialog(this, "없는 아이디입니다. 다시 입력하세요.");
            tfUserId.requestFocus();
            return;
        }else if(result == UserStateUtil.PWD_NONE_CHECK) {
            JOptionPane.showMessageDialog(this, "비밀번호가 틀렸습니다. 다시 입력하세요.");
            tfPwd.requestFocus();
            return;
        }else if(result == UserStateUtil.USER_CHECK) {
            String msg = userId + "로 로그인하였습니다.";
            JOptionPane.showMessageDialog(this, msg);

            UserStateUtil.userId = userId;
            UserStateUtil.userNo = dao.stateUserNo(UserStateUtil.userId);
            MainGUI2 f = new MainGUI2(userId);
            f.setVisible(true);

            this.dispose();
        }
    }

    private void join() {
        String userId = tfUserId.getText();
        String pwd = tfPwd.getText();

        JoinGUI f = new JoinGUI(userId, pwd, this);
        f.setVisible(true);
    }
}
